fix: 🐛 без редактирования цены
NewShiftStudio/gour-admin-front pull request #109
Opened 2022-10-24 13:49 UTC by avorokhta

2022-10-24 13:49 UTC, zolkinka commented
Task linked: [CU-3203vb8 Цены не сохраняются в админке для ролей "Организатор коллективной закупки" и "Юридическое лицо"](https://app.clickup.com/t/3203vb8)

2022-10-26 09:26 UTC, H0JLuk requested changes

2022-10-26 09:26 UTC, H0JLuk commented on src/components/UI/TextEditor/TextEditor.styles.ts
> +  quill: {},
пустой объект

2022-10-26 09:26 UTC, H0JLuk commented on src/types/index.d.ts
> +export type SxList = Record<string, SxProps | CSSProperties>;
`SxProps & CSSProperties` по-идее

2022-11-08 14:10 UTC, H0JLuk approved these changes

2022-11-08 14:10 UTC, merged