fix: 🐛 удаление пользователей и их роли
NewShiftStudio/gour-admin-front pull request #110
Opened 2022-10-25 14:33 UTC by avorokhta

2022-10-25 14:33 UTC, zolkinka commented
Task linked: [CU-47ze3mh Невозможно удалить пользователя](https://app.clickup.com/t/47ze3mh)

2022-10-26 10:12 UTC, H0JLuk requested changes

2022-10-26 10:12 UTC, H0JLuk commented on src/components/Users/CreateForm/CreateForm.tsx
> +  const submitHandler = (data: UserCreateDto) => onSubmit(data);
можно удалить функцию)

2022-10-26 10:12 UTC, H0JLuk commented on src/components/Users/Table/Table.tsx
> +        {[Roles.CLIENT, Roles.COMPANY, Roles.COLLECTIVE_PURCHASE].includes(user.role?.key as Roles) ? (
вынеси в функцию логику проверки

2022-10-26 10:12 UTC, H0JLuk commented on src/layouts/Private.tsx
> +          name: currentUser?.name || 'Иван',
тут идея в том, что Иван никогда не передастся?

2022-10-26 10:12 UTC, H0JLuk commented on src/types/entities/ClientRole.ts
> +} & Base;
мне кажется, `Base &` в начале более читаемым

2022-10-26 10:12 UTC, H0JLuk commented on src/types/entities/User.ts
> +} & Base;
и тут

2022-10-26 10:12 UTC, H0JLuk commented on src/types/entities/UserRole.ts
> +} & Base;
+

2022-10-26 10:12 UTC, H0JLuk commented on src/types/index.d.ts
>  export type SxType = Record<string, CSSProperties>;
удали тип SxType, если он нигде не используется

2022-10-26 10:12 UTC, H0JLuk commented on src/view/Users/List.tsx
> +  const { clients } = useGetClientsListQuery(undefined, {
здорово, уютненько)

2022-10-26 10:12 UTC, H0JLuk commented on src/view/Users/List.tsx
> +      {allUsers ? (
`.length` допиши, тк это всегда массив

2022-10-26 12:50 UTC, avorokhta commented on src/layouts/Private.tsx
> +          name: currentUser?.name || 'Иван',
просто старое дефолтное имя, могу поставить "Без имени"

2022-10-26 12:51 UTC, avorokhta commented on src/types/entities/ClientRole.ts
> +} & Base;
может на интерфейсы переписать как в магазине?

2022-10-26 12:51 UTC, avorokhta commented on src/types/entities/ClientRole.ts
> +} & Base;
хотя поставить в начало проще)

2022-10-26 13:41 UTC, H0JLuk approved these changes

2022-10-26 13:41 UTC, merged