feat: 🎸 система промокодов
NewShiftStudio/gour-admin-front pull request #122
Opened 2022-12-06 10:32 UTC by avorokhta

2022-12-06 10:32 UTC, zolkinka commented
Task linked: [TSX-4613 Добавить промокоды](https://app.clickup.com/t/4712744/TSX-4613)

2022-12-07 00:09 UTC, H0JLuk requested changes

2022-12-07 00:09 UTC, H0JLuk commented on src/types/entities/PromoCode.ts
> +export type PromoCode = Base & {
нужно было оставить нейминг BaseEntity, не совсем понятен смысл без контекста

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Create.tsx
> +import { useTo } from '../../hooks/useTo';
глобальный импорт)

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Edit.tsx
> +import { useTo } from '../../hooks/useTo';
и тут абсолютный импорт

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Edit.tsx
> +      eventBus.emit(EventTypes.notification, {
мб _dispatchNotification_  написать удобнее, чтобы не юзать 3 импорта для уведомлений?

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Edit.tsx
> +      eventBus.emit(EventTypes.notification, {
и тут

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Edit.tsx
> +  if (!isLoading && isError) {
`!isLoading` лишний

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/Edit.tsx
> +  if (!isLoading && !isError && !promoCode) {
`!isLoading && !isError` лишние)

2022-12-07 00:09 UTC, H0JLuk commented on src/view/PromoCodes/List.tsx
> +        {!isLoading && !isError && promoCode.length === 0 && <Typography variant='h2'>Нет промокодов</Typography>}
`isSuccess` есть в хуке rtk, чтобы 2 условия не юзать (я про ` !isLoading && !isError`)

2022-12-07 14:28 UTC, avorokhta commented on src/components/PromoCode/CategorySelectForm/CategorySelectForm.tsx
> +  category.subCategories.every(midCategory => isMidCategorySelected(midCategory, selected));
та вот даже не знаю пока
тип продукта считается выбранным, если у его категорий выбраны все подкатегории 
как по-другому то...

2022-12-08 05:39 UTC, H0JLuk requested changes

2022-12-08 05:39 UTC, H0JLuk commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
`invalidatesTags: (_res, _error, { id }) => [{ type: 'PromoCode', id }],` так

2022-12-08 12:47 UTC, avorokhta commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
так нельзя, arg содержит отправляемую dto

2022-12-08 12:47 UTC, avorokhta commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
может с providesTags путаешь, там такое возможно

2022-12-09 08:59 UTC, H0JLuk commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
![image](https://user-images.githubusercontent.com/56842874/206664217-7146498a-3c2f-4aab-9e2c-c72b2a322f0f.png)

2022-12-09 09:12 UTC, avorokhta commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
я понимаю что там такое есть, но по факту так нельзя)

2022-12-09 09:20 UTC, avorokhta commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
<img width="603" alt="Снимок экрана 2022-12-09 в 12 18 54" src="https://user-images.githubusercontent.com/93992220/206667878-b12b13e5-0d63-407b-8525-8294849f51e0.png">
<img width="586" alt="Снимок экрана 2022-12-09 в 12 19 24" src="https://user-images.githubusercontent.com/93992220/206667962-2e73d8c8-ce20-44c4-80e8-db15a8f200f4.png">

в arg подставляется dto, то есть указать так id получится только в обновлении и удалении

2022-12-09 09:22 UTC, avorokhta commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
или ты так и хотел?
а в createPromoCode вместо id указать LIST?

2022-12-12 08:46 UTC, H0JLuk commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
да, я имел ввиду передавать `arg`, где можно)

2022-12-12 08:57 UTC, H0JLuk commented on src/api/promoCodeApi.ts
> +        invalidatesTags: [{ type: 'PromoCode', id: 'LIST' }],
в createPromoCode нельзя будет из аргумента id достать, тк его там нет, ты прав)

2022-12-13 09:25 UTC, H0JLuk approved these changes

2022-12-13 09:26 UTC, merged