Feat categories modal 375
NewShiftStudio/gour-admin-front pull request #77
Opened 2022-09-19 13:29 UTC by MikleBr

2022-09-20 22:42 UTC, mirageN1349 requested changes

2022-09-20 22:42 UTC, mirageN1349 commented on src/view/Categories/List.tsx
> +  const editingCategory = categories?.find(it => it.id === selectedCategoryId); // FIXME: переписать функцию
Переписал?

2022-09-23 15:22 UTC, H0JLuk requested changes

2022-09-23 15:22 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +      <CreateCategoryModal
исправь ошибки типов

2022-09-23 15:22 UTC, H0JLuk commented on src/components/Categories/CreateForm/CreateForm.tsx
> +          if (!subCategory) return null;
судя по .reduce, не его должно быть

2022-09-23 15:22 UTC, H0JLuk commented on src/components/Categories/CreateForm/CreateForm.tsx
> +      const mutableCategoriesObj = JSON.parse(
const {'твой id':_extra , ...rest} = current;
такая конструкция есть

2022-09-23 15:22 UTC, H0JLuk commented on src/components/Categories/CreateForm/CreateForm.tsx
> +        JSON.stringify(category)
идентично

json.parse(json.stringify()) плохо использовать из-за перфоманса, да и практика не лучшая

2022-09-23 15:22 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +  const editingCategory = categories?.find(it => it.id === selectedCategoryId); // FIXME: переписать функцию
+

2022-09-23 15:22 UTC, H0JLuk commented on src/components/UI/Modal/Modal.styles.ts
> +    padding: '24px',
добавь скролл, на маленьких экранах ей плохо

2022-09-23 15:22 UTC, H0JLuk commented on src/components/Categories/CreateForm/validation.ts
> +  title: yup.string().required('Название не должно быть пустым'),
добавь валидацию для подкатегорий

https://github.com/jquense/yup/issues/130

2022-09-23 15:22 UTC, H0JLuk commented on src/components/Categories/CreateForm/CreateForm.tsx
> +  const canCreateCategory =
валидация должна заменить .every

2022-09-23 17:20 UTC, H0JLuk approved these changes

2022-09-23 17:22 UTC, mirageN1349 approved these changes

2022-09-23 17:35 UTC, merged