Feat new categories page
NewShiftStudio/gour-admin-front pull request #88
Opened 2022-09-27 09:15 UTC by MikleBr

2022-09-28 06:53 UTC, H0JLuk requested changes

2022-09-28 06:53 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +      if (openedProductTypeId === -1) {
на null тогда уж замени

2022-09-28 07:59 UTC, H0JLuk requested changes

2022-09-28 07:59 UTC, H0JLuk commented on src/components/Categories/ProductType/ProductType.tsx
>                Редактировать
на клик навесь stopPropagation хотя бы, чтобы аккордеон не открывался при нажатии на кнопки ред. и удалить

2022-09-28 07:59 UTC, H0JLuk commented on src/components/Categories/ProductTypeModal/ProductTypeModal.tsx
> +      title="Создание типа товара"
при редактировании заголовок не меняется

2022-09-28 21:20 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +    >(undefined);
и не забудь убрать его)

2022-09-29 11:24 UTC, MikleBr commented on src/components/Product/SelectForm/selectHelper.ts
> +    const isPassedBySelects = true || filterProductBySelects(product, selectsValues); // FIXME:
Твои коды((

2022-09-29 13:01 UTC, MikleBr commented
https://app.clickup.com/t/4712744/TSX-1753

2022-09-29 13:25 UTC, H0JLuk submitted a review, later dismissed

2022-09-29 13:27 UTC, H0JLuk approved these changes

2022-09-29 13:29 UTC, merged