Выбор участия категории в скидочной программе
NewShiftStudio/gour-admin-front pull request #94
Opened 2022-10-11 10:18 UTC by MikleBr

2022-10-11 10:18 UTC, zolkinka commented
Task linked: [TSX-3783 Доработка подкатегорий, добавление возможности выбора участия в скидочной программе](https://app.clickup.com/t/4712744/TSX-3783)

2022-10-11 10:57 UTC, H0JLuk requested changes

2022-10-11 10:57 UTC, H0JLuk commented on src/@types/dto/category/update.dto.ts
> +    hasDiscount?: boolean;
прости, наврал, с бэка не может придти undefined

2022-10-11 10:57 UTC, H0JLuk commented on src/@types/entities/Category.ts
> +  hasDiscount?: boolean;
и тут удоли "?"

2022-10-11 10:57 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +        hasDiscount: hasDiscount === 'Yes',
и тут измени

2022-10-11 10:57 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +    console.log('data :', data);
лог

2022-10-12 06:45 UTC, H0JLuk requested changes

2022-10-12 06:45 UTC, H0JLuk commented on src/components/Categories/CreateOrEditForm/CreateOrEditForm.tsx
> +          <FormControlLabel value="Yes" control={<Radio />} label="Да" />
value поменяй)

2022-10-12 06:45 UTC, H0JLuk commented on src/view/Categories/List.tsx
> +        hasDiscount: hasDiscount === 'Yes',
вроде как не поменял на enum

2022-10-12 08:07 UTC, merged